Repository jfrog/jfrog-cli, pull requests merged in 2022-12, with the labels that each got.

#1777 Gradle - Publish bom files when 'java-platform' plugin applied
  go.mod
  go.sum
Labels: improvement

#1771 Can't upload a directory which name includes '()'
  artifactory_test.go
  go.mod
  go.sum
  testdata/b/b(b)/c(c).in
  testdata/b/b(b)/d.in
  testdata/filespecs/upload_file_with_parentheses.json
  testdata/filespecs/upload_file_with_parentheses_and_placeholders.json
  testdata/filespecs/upload_file_with_parentheses_and_placeholders_and_regexp.json
  testdata/filespecs/upload_file_with_parentheses_and_regexp.json
  utils/tests/consts.go
Labels: bug

#1770 Suggest using Docker scan in Docker commands
  buildtools/cli.go
  docs/buildtools/docker/help.go
Labels: improvement

#1729 Upload - Take into account the repository name with exclude pattern and include directory flags
  artifactory_test.go
  go.mod
  go.sum
  testdata/filespecs/upload_exclude_include_dir.json
  testdata/filespecs/upload_exclude_include_dirs.json
  testdata/filespecs/upload_exclude_include_dirs_flat.json
  testdata/filespecs/upload_exclude_repo.json
  testdata/filespecs/upload_exclude_repo_content.json
  testdata/filespecs/upload_exclude_repo_content_part_2.json
  utils/tests/consts.go
Labels: bug

#1786 Fix docker scan by repo-path
  go.mod
  go.sum
  scan/cli.go
Labels: bug

#1765 Transfer config - Add preflight check option
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#1789 Add .frogbot/frogbot-config.yml
  .frogbot/frogbot-config.yml
Labels: ignore for release
