Repository jfrog/jfrog-cli, pull requests merged in 2022-09, with the labels that each got.

#1678 Fix Nuget dependencies calculation issue
  go.mod
  go.sum
  xray_test.go
Labels: bug, safe to test, ignore for release

#1680 Improve artifactory tests
  artifactory_test.go
  docker_test.go
  inttestutils/buildinfo.go
  inttestutils/docker.go
Labels: safe to test, ignore for release

#1681 Sync-deletes - The wrong folders are deleted when uploading files with uppercase names
  artifactory_test.go
  go.mod
  go.sum
  testdata/syncdeletes/industrial-os-7.4.3/TestReport/testfile.txt
  testdata/syncdeletes/industrial-os-7.4.3/apt/testfile.txt
  testdata/syncdeletes/industrial-os-7.4.3/docs/testfile.txt
  testdata/syncdeletes/industrial-os-7.4.3/images/testfile.txt
  testdata/syncdeletes/industrial-os-7.4.3/oss/testfile.txt
Labels: bug, safe to test

#1684 Action-remove-label - Grant read/write repository permission
  .github/workflows/removeLabel.yml
Labels: ignore for release

#1685 Add JFrog CLI version debug msg
  go.mod
  go.sum
  main.go
Labels: ignore for release

#1687 Improvement - fix technology naming
  artifactory_test.go
  go.mod
  go.sum
  scan/cli.go
Labels: improvement

#1672 Add installDataTransferPlugin to transfer tests
  .github/workflows/transferTests.yml
  README.md
  transfer_test.go
  utils/tests/utils.go
Labels: ignore for release

#1641 Improve bugs reporting view to Github's new Issue Form UI
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ignore for release

#1690 Remove Dotnet add source tests
  go.mod
  go.sum
  nuget_test.go
Labels: ignore for release

#1696 Transfer - Support HTTP proxy
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#1691 Add Poetry Support
  .github/workflows/pythonTests.yml
  .github/workflows/xrayTests.yml
  README.md
  artifactory/cli.go
  buildtools/cli.go
  docs/buildtools/poetry/help.go
  docs/buildtools/poetryconfig/help.go
  go.mod
  go.sum
  inttestutils/buildinfo.go
  pip_test.go
  pipenv_test.go
  poetry_test.go
  pyproject.toml
  testdata/poetry/poetry.yaml
  testdata/poetry/poetryproject/poetry.lock
  testdata/poetry/poetryproject/pyproject.toml
  testdata/poetry_remote_repository_config.json
  testdata/poetry_virtual_repository_config.json
  testdata/xray/python/poetry/poetry.lock
  testdata/xray/python/poetry/pyproject.toml
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
  utils/tests/utils.go
  xray_test.go
Labels: new feature
