Repository jfrog/jfrog-cli, pull requests merged in 2022-10, with the labels that each got.

#1705 Add links to tests' badges
  README.md
Labels: ignore for release

#1716 Fix missing poetry test params
  .github/workflows/pythonTests.yml
  main_test.go
Labels: ignore for release

#1719 Remove unnecessary dummy test file
  pyproject.toml
Labels: ignore for release

#1722 Transfer files - Add status flag
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: new feature

#1699 Add BypassArchiveLimits flag for Scan commands
  go.mod
  go.sum
  scan/cli.go
  utils/cliutils/commandsflags.go
  xray_test.go
Labels: improvement

#1728 Make The Poetry Test version fixed
  .github/workflows/pythonTests.yml
Labels: ignore for release

#1745 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1746 Add Frogbot scan-and-fix
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release
