Repository jfrog/jfrog-cli, pull requests merged in 2022-11, with the labels that each got.

#1748 Add distribution sync timeout test
  distribution_test.go
  go.mod
  go.sum
Labels: ignore for release

#1750 Fix docker file transfer in phase 2
  go.mod
  go.sum
Labels: bug

#1747 Upgrade to GO 1.19
  .github/workflows/accessTests.yml
  .github/workflows/analysis.yml
  .github/workflows/artifactoryTests.yml
  .github/workflows/distributionTests.yml
  .github/workflows/dockerTests.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/goTests.yml
  .github/workflows/gradleTests.yml
  .github/workflows/mavenTests.yml
  .github/workflows/npmTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/pluginsTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/transferTests.yml
  .github/workflows/xrayTests.yml
  Jenkinsfile
  README.md
  artifactory/cli.go
  artifactory_test.go
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  buildinfo_test.go
  completion/shells/bash/bash.go
  completion/shells/fish/fish.go
  completion/shells/generate_scripts_test.go
  completion/shells/zsh/zsh.go
  distribution/cli.go
  distribution_test.go
  docker_test.go
  general/cisetup/cisetup.go
  go.mod
  go.sum
  inttestutils/distribution.go
  maven_test.go
  nuget_test.go
  schema/filespecschema_test.go
  utils/progressbar/readerprogressbar.go
  utils/tests/container.go
  utils/tests/utils.go
Labels: improvement

#1734 Upgrade GO to 1.19
  .github/workflows/tests.yml
  Jenkinsfile
  artifactory/cli.go
  artifactory_test.go
  bintray_test.go
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  buildinfo_test.go
  completion/shells/bash/bash.go
  completion/shells/generate_scripts_test.go
  completion/shells/zsh/zsh.go
  distribution_test.go
  general/cisetup/cisetup.go
  go.mod
  go.sum
  go_test.go
  inttestutils/distribution.go
  maven_test.go
  npm_test.go
  nuget_test.go
  plugins/utils/signatureutils.go
  plugins_test.go
  schema/filespecschema_test.go
  utils/progressbar/readerprogressbar.go
  utils/tests/utils.go
Labels: safe to test, improvement

#1760 Transfer config - Support setting the work dir
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#1738 Refactor README badges
  README.md
Labels: ignore for release

#1755 Transfer - adding pre-check flag option to run checks on the source
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#1744 Add install data transfer plugin command
  artifactory/cli.go
  docs/artifactory/installtransfer/help.go
  go.mod
  go.sum
  inttestutils/transfer.go
  transfer_test.go
  utils/cliutils/commandsflags.go
Labels: new feature

#1762 Transfer - Add test to identify unsupported directory structure
  go.mod
  go.sum
  transfer_test.go
Labels: ignore for release

#1767 Fix calling install transfer plugin in tests
  artifactory/cli.go
  docs/artifactory/transferplugininstall/help.go
  transfer_test.go
  utils/cliutils/commandsflags.go
Labels: bug
