Repository jfrog/jfrog-cli, pull requests merged in 2022-07, with the labels that each got.

#1590 Fix Download/Upload progress bar log path and improve audit code
  artifactory/cli.go
  general/envsetup/envsetup.go
  plugins/commands/install.go
  scan/cli.go
  utils/progressbar/filesprogressbar.go
  xray/cli.go
Labels: bug, safe to test

#1596 Failure to calculate final results summary during upload
  artifactory_test.go
  go.mod
  go.sum
Labels: bug, safe to test

#1598 Add a conclusion after config-transfer
  artifactory/cli.go
Labels: improvement

#1602 Update the Go version used to build JFrog CLI to 1.17.12
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
Labels: 🐸 frogbot scan, improvement

#1604 Stop and exit JFrog CLI if one of the transfer's writers fails to write
  go.mod
  go.sum
Labels: safe to test, improvement

#1609 Show current transfer settings
  go.mod
  go.sum
Labels: improvement

#1580 Added Intro Command
  build/deb_rpm/v2/build-scripts/deb-install.sh
  build/deb_rpm/v2/build-scripts/rpm-install.sh
  build/installcli/jf.sh
  build/npm/v2-jf/init.js
  build/npm/v2/init.js
  build/setupcli/jf.sh
  general/envsetup/envsetup.go
  main.go
  utils/cliutils/commandsflags.go
Labels: safe to test, new feature

#1613 Fix Specific Maven audit and improve specific audit tests
  go.mod
  go.sum
  scan/cli.go
  xray_test.go
Labels: bug, safe to test

#1618 Added Mac ARM64 CLI Support
  Jenkinsfile
  build/getcli/jf.sh
  build/getcli/jfrog.sh
  build/installcli/jf.sh
  build/installcli/jfrog.sh
  build/npm/v2-jf/init.js
  build/npm/v2/init.js
  build/setupcli/jf.sh
  plugins/commands/utils/utils.go
Labels: safe to test

#1625 Add 'working threads' progress bar to files-transfer command
  go.mod
  go.sum
Labels: safe to test, improvement
