Repository jfrog/jfrog-cli, pull requests merged in 2022-08, with the labels that each got.

#1630 Update go.mod
  go.mod
  go.sum
Labels: safe to test, ignore for release

#1632 Add transfer integration tests
  .github/workflows/transferTests.yml
  README.md
  artifactory_test.go
  distribution_test.go
  docker_test.go
  go.mod
  go.sum
  gradle_test.go
  inttestutils/artifactory.go
  inttestutils/transfer.go
  main.go
  main_test.go
  maven_test.go
  plugins_test.go
  transfer_test.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: safe to test, ignore for release

#1633 Fix get all release bundles API for distribution test
  artifactory_test.go
  inttestutils/buildinfo.go
  inttestutils/distribution.go
Labels: safe to test, ignore for release

#1635 Add integration test for transferring build-info
  go.mod
  go.sum
  inttestutils/transfer.go
  transfer_test.go
  utils/tests/utils.go
Labels: safe to test, ignore for release

#1637 Fix 401 error on transfer-config
  artifactory/cli.go
Labels: bug, safe to test

#1638 Fix maven & npm tests
  .github/workflows/tests.yml
  artifactory_test.go
  testdata/maven_repository_config1.json
  testdata/maven_repository_config2.json
  testdata/npm/npmpostinstall/package.json
Labels: safe to test, ignore for release

#1643 Unarchive fail with legit symlinks
  go.mod
  go.sum
Labels: bug, safe to test

#1647 Remove emoji from progress bar headlines if terminal non-supported
  go.mod
  go.sum
  utils/progressbar/filesprogressbar.go
Labels: bug, safe to test

#1648 Remove unnecessary search from interactive selection and replace selection emoji(🐸) on windows
  general/cisetup/cisetup.go
  go.mod
  go.sum
Labels: safe to test, improvement

#1644 Transfer - Add integration test for properties
  transfer_test.go
Labels: safe to test, ignore for release

#1649 Transfer - Missing repository in the repositories summary
  go.mod
  go.sum
  inttestutils/transfer.go
  transfer_test.go
Labels: bug, safe to test

#1601 Added 'sarif' to audit format flags description
  utils/cliutils/commandsflags.go
Labels: safe to test, new feature

#1650 Fix setupcli typo
  build/setupcli/jf.sh
Labels: bug, safe to test

#1651 Remove unnecessary log file path on setup command and rename Server Token to Config Token
  docs/config/exportcmd/help.go
  docs/config/importcmd/help.go
  plugins/commands/install.go
  utils/progressbar/filesprogressbar.go
Labels: improvement

#1652 Handle typo in access.bootstrap.json
  go.mod
  go.sum
Labels: bug, safe to test

#1657 Update tests.yml , Fix python tests and add Cache and Lint
  .github/workflows/tests.yml
Labels: ignore for release

#1656 Added transferfiles diff test
  .github/workflows/transferTests.yml
  transfer_test.go
Labels: safe to test, improvement

#1655 V1 - Update Go to 1.17.13, add Mac ARM6 Support, update Archiver to latest, Fix tests
  Jenkinsfile
  artifactory_test.go
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  build/getCli.sh
  build/npm/init.js
  go.mod
  go.sum
  plugins/commands/utils/utils.go
Labels: safe to test, 🐸 frogbot scan, improvement

#1660 Fix login suspension in transfer-config
  artifactory/cli.go
  go.mod
  go.sum
Labels: bug, safe to test

#1497 Automatically unlabel 'safe to test' after tests run
  .github/workflows/tests.yml
  testdata/xray/nuget/multi/TestApp1/obj/TestApp1.csproj.nuget.dgspec.json
  testdata/xray/nuget/multi/TestApp1/obj/TestApp1.csproj.nuget.g.props
  testdata/xray/nuget/multi/TestApp1/obj/TestApp1.csproj.nuget.g.targets
  testdata/xray/nuget/multi/TestApp1/obj/project.assets.json
Labels: safe to test, ignore for release

#1639 Transfer files --ignore-state flag
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: new feature

#1665 Add CLI version debug message before each command execution
  main.go
Labels: improvement

#1669 V1 - Update Go to 1.18
  .github/release.yml
  .github/workflows/tests.yml
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  go.mod
  go.sum
Labels: safe to test, improvement

#1664 Add JFROG_CLI_FAIL_NO_OP environment variable
  artifactory/cli.go
  artifactory_test.go
  buildtools/cli.go
  docs/artifactory/copy/help.go
  docs/artifactory/delete/help.go
  docs/artifactory/deleteprops/help.go
  docs/artifactory/download/help.go
  docs/artifactory/gradle/help.go
  docs/artifactory/move/help.go
  docs/artifactory/mvn/help.go
  docs/artifactory/search/help.go
  docs/artifactory/setprops/help.go
  docs/artifactory/upload/help.go
  docs/buildtools/gradle/help.go
  docs/buildtools/mvn/help.go
  docs/common/env.go
  docs/common/help.go
  docs/common/helputils.go
  docs/plugin/install/help.go
  docs/plugin/publish/help.go
  go.mod
  go.sum
  plugins/cli.go
  utils/cliutils/utils.go
Labels: improvement

#1611 Added pip requirements file flag
  scan/cli.go
  testdata/xray/python/pip/requirements.txt
  utils/cliutils/commandsflags.go
  xray_test.go
Labels: improvement

#1668 Avoid old snapshots/tags cleanup after transfer
  go.mod
  go.sum
Labels: bug

#1629 Fix Intro Command
  build/npm/v2-jf/init.js
  build/npm/v2/init.js
  main.go
Labels: improvement

#1673 Update Dependencies
  .github/workflows/analysis.yml
  go.mod
  go.sum
Labels: improvement

#1676 Fix intro command message
  main.go
Labels: bug
