Repository jfrog/jfrog-cli, pull requests merged in 2023-03, with the labels that each got.

#1852 Use the latest V3 alpine in the slim image
  build/docker/slim/Dockerfile
Labels: improvement

#1854 Fix audit in release
  Jenkinsfile
Labels: ignore for release

#1856 Update core changes
  go.mod
  go.sum
  nuget_test.go
Labels: ignore for release

#1804 Use wrapper by default in audit maven & gradle
  scan/cli.go
  utils/cliutils/commandsflags.go
Labels: new feature

#1870 Use gradle 7.6 version on tests
  .github/workflows/gradleTests.yml
  .github/workflows/xrayTests.yml
Labels: ignore for release

#1871 Improve Xray tests
  go.mod
  go.sum
  utils/tests/utils.go
  xray_test.go
Labels: improvement

#1866 Add test for uploading working directory as archive
  artifactory_test.go
  testdata/filespecs/upload_archive_wd.json
  utils/tests/consts.go
Labels: ignore for release

#1864 Transfer - update tests following restructure of snapshot
  go.mod
  go.sum
  transfer_test.go
  utils/tests/consts.go
Labels: ignore for release

#1874 Update go.mod
  go.mod
  go.sum
Labels: ignore for release

#1869 Add more tests to the ANT pattern
  artifactory_test.go
  go.mod
  go.sum
  testdata/filespecs/upload_exclude_include_dir_ant_pattern.json
  testdata/filespecs/upload_exclude_include_dir_ant_pattern2.json
  utils/tests/consts.go
Labels: ignore for release

#1881 Fix Distribution Tests and delay Windows Poetry Test
  distribution_test.go
  maven_test.go
  poetry_test.go
  utils/tests/utils.go
Labels: ignore for release

#1878 Support providing password/accessToken via Stdin
  .github/workflows/cla.yml
  artifactory_test.go
  config/cli.go
  go.mod
  go.sum
  missioncontrol/cli.go
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: new feature

#1886 Fix maven test
  .github/workflows/mavenTests.yml
Labels: ignore for release

#1882 GitLab - Support downloading JFrog CLI from remote repository
  Jenkinsfile
  build/gitlab/.setup-jfrog.yml
  build/gitlab/v2/.setup-jfrog-unix.yml
  build/gitlab/v2/.setup-jfrog-windows.yml
Labels: improvement

#1875 Support providing an encryption key by environment variable
  artifactory_test.go
  docs/common/env.go
  go.mod
  go.sum
Labels: new feature

#1890 Fix upload in Jenkinsfile
  Jenkinsfile
Labels: ignore for release
