Repository jfrog/jfrog-cli, pull requests merged in 2023-09, with the labels that each got.

#2181 Update core dependency
  go.mod
  go.sum
  pip_test.go
  scan/cli.go
  xray_test.go
Labels: safe to test, ignore for release

#2183 Improve actions cache
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-repository.yml
  .github/workflows/mavenTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/xrayTests.yml
Labels: ignore for release

#2186 Run Xray tests with latest analyzer manager version
  .github/workflows/xrayTests.yml
  go.mod
  go.sum
Labels: ignore for release

#2187 Updating and Adding new tests for NuGet projects
  testdata/xray/nuget/single4.0/core/Multi1.cs
  testdata/xray/nuget/single4.0/core/Properties/AssemblyInfo.cs
  testdata/xray/nuget/single4.0/core/core.csproj
  testdata/xray/nuget/single4.0/core/core.nuspec
  testdata/xray/nuget/single4.0/core/packages.config
  testdata/xray/nuget/single4.0/example.sln
  testdata/xray/nuget/single5.0/ClassLibrary1/ClassLibrary1.csproj
  testdata/xray/nuget/single5.0/TestSolution.sln
  xray_test.go
Labels: ignore for release

#2202 Improve download scripts
  build/getcli/jf.sh
  build/getcli/jfrog.sh
  build/installcli/jf.sh
  build/installcli/jfrog.sh
  build/setupcli/jf.sh
Labels: improvement

#2203 Rename tokens refresh thresholds
  access_test.go
  artifactory_test.go
  go.mod
  go.sum
Labels: ignore for release

#2196 Add Third party contextual analysis flag
  go.mod
  scan/cli.go
  utils/cliutils/commandsflags.go
Labels: improvement

#2205 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#2206 Promoted version to v2.47.0
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/frogbot-scan-repository.yml
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2185 Enable lifecycle release bundle distribute
  documentation/CLI-for-JFrog-Lifecycle.md
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  testdata/filespecs/search_all_dev_repo.json
  utils/tests/consts.go
Labels: new feature

#2209 Promoted version to 2.48.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2214 Align changes with core
  artifactory_test.go
  go.mod
  go.sum
  scan/cli.go
Labels: ignore for release

#2180 Add Sast tests
  .github/workflows/xrayTests.yml
  testdata/xray/jas-test/requirements.txt
  testdata/xray/jas-test/sast/flask_webgoat/__init__.py
  testdata/xray/jas-test/sast/flask_webgoat/ui.py
  testdata/xray/jas-test/sast/result.sarif
  testdata/xray/jas-test/sast/run.py
  xray_test.go
Labels: ignore for release

#2103 Upload - Add timezone to each zip file before uploading
  artifactory_test.go
Labels: ignore for release

#2226 Fix lifecycle documentation
  documentation/CLI-for-JFrog-Lifecycle.md
Labels: ignore for release
