Repository jfrog/jfrog-cli, pull requests merged in 2023-10, with the labels that each got.

#2199 Support JFrog Apps Config file
  testdata/xray/jas-config/.jfrog/jfrog-apps-config.yml
  testdata/xray/jas-config/iac/azure/vpc/module.tf
  testdata/xray/jas-config/iac/azure/vpc/outputs.tf
  testdata/xray/jas-config/iac/azure/vpc/variables.tf
  testdata/xray/jas-config/iac/azure/vpc/versions.tf
  testdata/xray/jas-config/iac/azure/vpc_pp/module.tf
  testdata/xray/jas-config/iac/azure/vpc_pp/outputs.tf
  testdata/xray/jas-config/iac/azure/vpc_pp/variables.tf
  testdata/xray/jas-config/iac/azure/vpc_pp/versions.tf
  testdata/xray/jas-config/iac/gcp/k8s-oss/files/chk_k8s_nat
  testdata/xray/jas-config/iac/gcp/k8s-oss/module.tf
  testdata/xray/jas-config/iac/gcp/k8s-oss/outputs.tf
  testdata/xray/jas-config/iac/gcp/k8s-oss/variables.tf
  testdata/xray/jas-config/iac/gcp/k8s-oss/versions.tf
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/files/chk_k8s_nat
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/module.tf
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/outputs.tf
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/rbac.tf
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/variables.tf
  testdata/xray/jas-config/iac/gcp/k8s-pipelines-bp/versions.tf
  testdata/xray/jas-config/main.py
  testdata/xray/jas-config/requirements.txt
  testdata/xray/jas-config/sast/flask_webgoat/__init__.py
  testdata/xray/jas-config/sast/flask_webgoat/ui.py
  testdata/xray/jas-config/sast/result.sarif
  testdata/xray/jas-config/sast/run.py
  testdata/xray/jas-config/secrets/more_secrets/key
  testdata/xray/jas-config/secrets/more_secrets/sequence
  testdata/xray/jas-config/secrets/secret_generic/blacklist
  testdata/xray/jas-config/secrets/secret_generic/gibberish
  xray_test.go
Labels: improvement

#2193 Support Platform Access Token
  access_test.go
  artifactory/cli.go
  artifactory_test.go
  docs/artifactory/accesstokencreate/help.go
  docs/general/token/help.go
  general/token/cli.go
  go.mod
  go.sum
  main.go
  main_test.go
  utils/accesstoken/utils.go
  utils/cliutils/cli_consts.go
  utils/cliutils/commandsflags.go
Labels: new feature

#2234 Fix pip tests
  pip_test.go
Labels: ignore for release

#2237 Temporary skip Pipenv tests
  pipenv_test.go
Labels: ignore for release

#2236 Fix scripts test for npm install
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2240 Fix install CLI with sudo
  build/installcli/jf.sh
  build/installcli/jfrog.sh
  build/setupcli/jf.sh
Labels: bug

#2241 Promoted version to 2.49.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2244 Promoted version to 2.49.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2246 Remove unnecessary files in npm installer
  Jenkinsfile
Labels: bug

#2252 Add jq to the slim Docker image
  build/docker/slim/Dockerfile
Labels: improvement

#2258 Fix installer for npm v10+
  build/npm/v2-jf/init.js
  build/npm/v2/init.js
Labels: bug

#2249 Add --bypass-archive-inspection flag to docs
  documentation/CLI-for-JFrog-Artifactory.md
Labels: ignore for release

#2250 Windows binary link should be AMD instead of ARM
  .github/RELEASE_LINK_TEMPLATE.md
Labels: ignore for release

#2264 Fix TestAccessTokenCreate
  access_test.go
Labels: ignore for release

#2262 Add Yarn V1 test with `NODE_ENV`
  go.mod
  go.sum
  xray_test.go
Labels: ignore for release

#2266 Update Jenkinsfile go version to 1.20.10
  Jenkinsfile
Labels: improvement

#2269 Support running npm install without package.json
  go.mod
  go.sum
  npm_test.go
Labels: improvement

#2277 Promoted version to 2.50.3
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2281 Promoted version to 2.50.4
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2282 Command results reader close error is ignored
  access_test.go
  utils/cliutils/utils.go
Labels: bug

#2284 Fix TestPipInstallNativeSyntax in Windows
  .github/workflows/pythonTests.yml
Labels: ignore for release

#2285 Fix npm scripts tests
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2288 Update docs links
  README.md
  build/chocolatey/v2-jf/jfrog-cli-v2-jf.nuspec
  build/chocolatey/v2/jfrog-cli.nuspec
  build/deb_rpm/v2-jf/deb/debian/control
  build/deb_rpm/v2/deb/debian/control
  build/npm/v2-jf/README.md
  build/npm/v2/README.md
  guides/getting-started-with-jfrog-using-the-cli.md
Labels: ignore for release
