Repository jfrog/jfrog-cli, pull requests merged in 2023-08, with the labels that each got.

#2110 Remove deprecated pkg/errors
  go.mod
  go.sum
  utils/cliutils/codegangstautils.go
  utils/cliutils/utils_test.go
Labels: ignore for release

#2099 Audit - added support for Yarn V1
  .github/workflows/xrayTests.yml
  go.mod
  go.sum
  testdata/xray/yarn-v2/.yarn/releases/yarn-3.2.1.cjs
  testdata/xray/yarn-v2/.yarnrc.yml
  testdata/xray/yarn-v2/package.json
  testdata/xray/yarn-v2/yarn.lock
  xray_test.go
Labels: new feature

#2113 Remove yarn 2+ restriction from audit flag description and docs
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/CLI-for-JFrog-Xray.md
  utils/cliutils/commandsflags.go
Labels: ignore for release

#2114 Promoted version to 2.45.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2118 Update frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release

#2121 Enable SSO login cmd
  docs/general/login/help.go
  main.go
Labels: new feature

#2130 Release Lifecycle Management documentation corrections
  documentation/CLI-for-JFrog-Lifecycle.md
Labels: ignore for release

#2136 Release lifecycle management docs updates
  documentation/CLI-for-JFrog-Lifecycle.md
Labels: ignore for release

#2139 Documentation updates
  documentation/CLI-for-JFrog-Lifecycle.md
Labels: ignore for release

#2140 Update CLI-for-JFrog-Lifecycle.md
  documentation/CLI-for-JFrog-Lifecycle.md
Labels: ignore for release

#2147 Update go.mod
  go.mod
  go.sum
Labels: ignore for release

#2152 Promote to v2.46.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2154 Add Web Login to the Documentation
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/JFrog-CLI.md
  documentation/images/login-page.png
  documentation/images/login-successful.png
Labels: ignore for release

#2151 Updating CLI doc to emphasize v1
  documentation/CLI-for-JFrog-Distribution.md
Labels: ignore for release

#2160 Add test to validate jas scanner inside paths that contain 'test'
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/frogbot-scan-repository.yml
  testdata/xray/jas-test/iac/azure/vpc/module.tf
  testdata/xray/jas-test/iac/azure/vpc/outputs.tf
  testdata/xray/jas-test/iac/azure/vpc/variables.tf
  testdata/xray/jas-test/iac/azure/vpc/versions.tf
  testdata/xray/jas-test/iac/azure/vpc_pp/module.tf
  testdata/xray/jas-test/iac/azure/vpc_pp/outputs.tf
  testdata/xray/jas-test/iac/azure/vpc_pp/variables.tf
  testdata/xray/jas-test/iac/azure/vpc_pp/versions.tf
  testdata/xray/jas-test/iac/gcp/k8s-oss/files/chk_k8s_nat
  testdata/xray/jas-test/iac/gcp/k8s-oss/module.tf
  testdata/xray/jas-test/iac/gcp/k8s-oss/outputs.tf
  testdata/xray/jas-test/iac/gcp/k8s-oss/variables.tf
  testdata/xray/jas-test/iac/gcp/k8s-oss/versions.tf
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/files/chk_k8s_nat
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/module.tf
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/outputs.tf
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/rbac.tf
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/variables.tf
  testdata/xray/jas-test/iac/gcp/k8s-pipelines-bp/versions.tf
  testdata/xray/jas-test/main.py
  testdata/xray/jas-test/requirements.txt
  testdata/xray/jas-test/secrets/more_secrets/key
  testdata/xray/jas-test/secrets/more_secrets/sequence
  testdata/xray/jas-test/secrets/secret_generic/blacklist
  testdata/xray/jas-test/secrets/secret_generic/gibberish
  xray_test.go
Labels: ignore for release

#2149 Added the "JFrog Cloud Transfer" docs content to the JFrog CLI's docs
  documentation/CLI-for-JFrog-Cloud-Transfer.md
  documentation/JFrog-CLI.md
  documentation/cli.ftmap
  documentation/images/transfer-1.png
  documentation/images/transfer-2.png
  documentation/images/transfer-3.png
  documentation/images/transfer-4.png
  documentation/images/transfer-5.png
Labels: ignore for release

#2163 Upgrade the analyzers-manager-app for improved advanced security scanning
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: improvement

#2166 Update the Frogbot workflows
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release

#2167 Upgrade client to 1.31.6 core to 2.41.3
  go.mod
  go.sum
  inttestutils/buildinfo.go
  xray_test.go
Labels: ignore for release

#2161 Support Gradle version catalog, configuration cache and lazy tasks
  .github/workflows/gradleTests.yml
  go.mod
  go.sum
  testdata/gradle/projectwithplugin/build.gradle
Labels: new feature

#2068 Support Lifecycle Release Bundle Distribute
  .github/workflows/lifecycleTests.yml
  distribution/cli.go
  distribution_test.go
  docs/lifecycle/distribute/help.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  utils/cliutils/commandsflags.go
  utils/distribution/distribute.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: ignore for release
