Repository jfrog/jfrog-cli, pull requests merged in 2023-05, with the labels that each got.

#1927 Update pythonTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/xrayTests.yml
Labels: ignore for release

#1918 Support for a new JFROG_CLI_RELEASES_REPO environment variable
  artifactory_test.go
  docs/artifactory/gradle/help.go
  docs/artifactory/mvn/help.go
  docs/buildtools/gradle/help.go
  docs/buildtools/mvn/help.go
  docs/common/env.go
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/JFrog-CLI.md
  go.mod
  go.sum
Labels: new feature

#1926 Add filters for Audit, Scan & Docker Scan
  documentation/CLI-for-JFrog-Xray.md
  go.mod
  go.sum
  scan/cli.go
  utils/cliutils/commandsflags.go
Labels: new feature

#1931 Promoted version to 2.37.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1934 Fix docker scan missing filter flags and wrong image name parsing
  go.mod
  go.sum
  scan/cli.go
  utils/cliutils/codegangstautils.go
  utils/cliutils/commandsflags.go
  xray_test.go
Labels: bug

#1938 Add the `transfer-files` command to the docs
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/images/transfer-files-progress.png
  documentation/images/transfer-files-status.png
Labels: ignore for release

#1929 Check latest CLI version and print warning if such exists
  docs/common/env.go
  go.mod
  go.sum
  go_test.go
  main.go
  plugins/commands/install.go
  plugins/commands/publish.go
  poetry_test.go
  unit_test.go
  utils/cliutils/cli_consts.go
  utils/cliutils/utils.go
  utils/cliutils/utils_test.go
  utils/tests/utils.go
Labels: new feature

#1951 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1937 Fix defer wrong inner function calls
  inttestutils/transfer.go
  npm_test.go
Labels: ignore for release

#1957 Fix NpmPackInstall failing test
  go_test.go
  npm_test.go
Labels: ignore for release

#1958 Add bash completion to the full Docker image
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
Labels: improvement

#1959 Reformat Readme markdown files and fix typos
  README.md
  build/npm/v2-jf/README.md
  build/npm/v2/README.md
  guides/getting-started-with-jfrog-using-the-cli.md
  guides/jfrog-cli-plugins-developer-guide.md
Labels: ignore for release

#1939 CVE applicability indication for `jf audit`
  documentation/CLI-for-JFrog-Xray.md
  documentation/images/audit-contextual-analysis.png
  go.mod
  go.sum
  xray_test.go
Labels: new feature

#1909 New curation-audit command
  docs/scan/curation/help.go
  go.mod
  go.sum
  scan/cli.go
  utils/cliutils/commandsflags.go
  xray_test.go
Labels: new feature

#1961 Promote version to 2.37.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  plugins/commands/utils/utils.go
  scan/cli.go
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1965 Update github.com/docker/distribution
  go.mod
  go.sum
Labels: ignore for release

#1947 Fix integration tests for conditionalUpdate
  gradle_test.go
  main_test.go
  maven_test.go
  npm_test.go
  testdata/filespecs/search_all_npm.json
Labels: improvement

#1925 Maven - Add support for no-proxy & https proxy
  go.mod
  go.sum
  maven_test.go
Labels: new feature

#1974 Fix warning message
  utils/cliutils/utils.go
Labels: ignore for release

#1977 FixNpm test condinial upload
  npm_test.go
Labels: ignore for release

#1975 Update the "CLI for JFrog Xray" docs
  documentation/CLI-for-JFrog-Xray.md
  documentation/images/audit.png
Labels: ignore for release

#1980 Update core changes
  go.mod
  go.sum
  utils/cliutils/utils.go
Labels: ignore for release

#1981 Avoid running tests and static analysis on tags
  .github/workflows/accessTests.yml
  .github/workflows/analysis.yml
  .github/workflows/artifactoryTests.yml
  .github/workflows/distributionTests.yml
  .github/workflows/dockerTests.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/goTests.yml
  .github/workflows/gradleTests.yml
  .github/workflows/mavenTests.yml
  .github/workflows/npmTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/pluginsTests.yml
  .github/workflows/podmanTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/scriptTests.yml
  .github/workflows/transferTests.yml
  .github/workflows/xrayTests.yml
Labels: ignore for release

#1982 Fix curation flaky test
  xray_test.go
Labels: ignore for release

#1983 Transfer Config Merge - Fix filter keys issue and add additional filter keys
  go.mod
  go.sum
Labels: improvement

#1986 Update Frogbot Scan and Fix workflow
  .github/workflows/frogbot-scan-and-fix.yml
Labels: ignore for release

#1978 Improve JFrog's dependencies download
  artifactory_test.go
  go.mod
  go.sum
  xray_test.go
Labels: improvement

#1989 Promoted version to 2.38.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1990 Fix GetRemoteFileDetails usage
  go.mod
  go.sum
  plugins/commands/install.go
Labels: ignore for release

#1991 Documentation fixes
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/CLI-for-JFrog-Xray.md
Labels: ignore for release

#1992 Promoted version to 2.38.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1994 Promoted version to 2.38.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1998 Promoted version to 2.38.3
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1953 Create tag and GitHub Release on release pipeline
  Jenkinsfile
Labels: ignore for release

#2002 Transfer - Exit on unrecoverable errors
  go.mod
  go.sum
Labels: improvement

#2003 Promote version to 2.38.4
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2005 Fix `Jf Audit` command entitlements service error
  go.mod
  go.sum
Labels: bug

#2006 Promoted version to 2.38.5
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release
