Repository jfrog/jfrog-cli, pull requests merged in 2023-11, with the labels that each got.

#2291 Fix TestPipInstallNativeSyntax in Ubuntu
  .github/workflows/pythonTests.yml
Labels: ignore for release

#2290 Transfer - Fix files count and size after stop
  go.mod
  go.sum
  transfer_test.go
Labels: bug

#2283 Audit SCA recursive scan
  scan/cli.go
  utils/cliutils/commandsflags.go
Labels: new feature

#2295 Fix Xray curation tests
  xray_test.go
Labels: ignore for release

#2296 Add tests for maven and gradle build timestamp
  go.mod
  go.sum
  gradle_test.go
  maven_test.go
Labels: ignore for release

#2297 Promoted version to 2.51.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2298 Release script - install npm earlier
  Jenkinsfile
Labels: ignore for release

#2299 Fine tune JFrog Advanced Security on this project
  .jfrog/jfrog-apps-config.yml
  Jenkinsfile
  testdata/npm/npmnpmrcproject/.npmrc
  testdata/xray/jas-config/sast/flask_webgoat/__init__.py
  testdata/xray/jas-test/sast/flask_webgoat/__init__.py
  utils/tests/consts.go
  xray_test.go
Labels: ignore for release

#2301 Promote version to 2.51.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2302 Add retries in script tests
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2320 Replace the old documentation content with a link to the new documentation site
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/CLI-for-JFrog-Cloud-Transfer.md
  documentation/CLI-for-JFrog-Curation.md
  documentation/CLI-for-JFrog-Distribution.md
  documentation/CLI-for-JFrog-Lifecycle.md
  documentation/CLI-for-JFrog-Mission-Control.md
  documentation/CLI-for-JFrog-Pipelines.md
  documentation/CLI-for-JFrog-Xray.md
  documentation/JFrog-CLI.md
  documentation/images/audit1.png
  documentation/images/audit2.png
  documentation/images/audit3.png
  documentation/images/docker-scan.png
  documentation/images/jf-ca-output.png
  documentation/images/jf-scan-output.png
  documentation/images/jfrog-cli-intro.png
  documentation/images/login-page.png
  documentation/images/login-successful.png
  documentation/images/transfer-1.png
  documentation/images/transfer-2.png
  documentation/images/transfer-3.png
  documentation/images/transfer-4.png
  documentation/images/transfer-5.png
  documentation/images/transfer-files-progress.png
  documentation/images/transfer-files-status.png
Labels: ignore for release

#2311 Transfer - Limit max AQL threads to 16
  go.mod
  go.sum
  inttestutils/transfer.go
Labels: improvement

#2322 Fix pipenv tests
  go.mod
  go.sum
  pipenv_test.go
Labels: ignore for release

#2323 Remove poetry integration tests for build-info
  .github/workflows/pythonTests.yml
  CONTRIBUTING.md
  main_test.go
  poetry_test.go
  testdata/poetry/poetry.yaml
  testdata/poetry/poetryproject/poetry.lock
  testdata/poetry/poetryproject/pyproject.toml
  utils/tests/consts.go
  utils/tests/utils.go
Labels: ignore for release

#2329 Fix flaky Lifecycle tests
  lifecycle_test.go
Labels: ignore for release

#2328 Synchronize branches on release
  Jenkinsfile
Labels: ignore for release

#2336 Update go.mod and go.sum
  go.mod
  go.sum
Labels: ignore for release
