Repository jfrog/jfrog-cli, pull requests merged in 2023-02, with the labels that each got.

#1811 JFrog CLI Docs
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/CLI-for-JFrog-Distribution.md
  documentation/CLI-for-JFrog-Mission-Control.md
  documentation/CLI-for-JFrog-Xray.md
  documentation/JFrog-CLI.md
  documentation/images/audit.png
  documentation/images/docker-scan.png
  documentation/images/jf-scan-output.png
Labels: ignore for release

#1826 Plugin install - return error if plugin not found
  plugins/commands/install.go
Labels: bug

#1821 Fix Docker fat-manifest test
  docker_test.go
  testdata/expected_fatmanifest_buildInfo.json
  utils/tests/consts.go
Labels: bug

#1825 Update FileSpec schema
  artifactory_test.go
  distribution_test.go
  schema/filespec-schema.json
  testdata/distribution/distribution_rules.json
  testdata/replication_push_create.json
  utils/tests/utils.go
Labels: improvement

#1831 File Spec schema - set sortBy property as type array of strings
  schema/filespec-schema.json
Labels: bug

#1842 Add Setup JFrog for GitLab to release
  Jenkinsfile
  build/gitlab/.setup-jfrog.yml
Labels: ignore for release

#1841 CLI doc for JFrog Pipelines
  documentation/CLI-for-JFrog-Pipelines.md
Labels: ignore for release

#1828 Add Advanced Security to Xray's offline DB sync
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
  xray/cli.go
  xray/cli_test.go
  xray_test.go
Labels: new feature
