Repository jfrog/jfrog-cli, pull requests merged in 2023-04, with the labels that each got.

#1892 Improvements to the indication of finished initialization for the docker daemon in tests
  docker_test.go
Labels: ignore for release

#1891 Upgrade release and tests to use Go 1.20.2
  .github/workflows/accessTests.yml
  .github/workflows/analysis.yml
  .github/workflows/artifactoryTests.yml
  .github/workflows/distributionTests.yml
  .github/workflows/dockerTests.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/goTests.yml
  .github/workflows/gradleTests.yml
  .github/workflows/mavenTests.yml
  .github/workflows/npmTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/pluginsTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/transferTests.yml
  .github/workflows/xrayTests.yml
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  go.mod
  utils/tests/utils.go
Labels: improvement

#1894 Fix lint issues and update dependencies
  .github/workflows/nugetTests.yml
  .github/workflows/xrayTests.yml
  artifactory/cli.go
  general/cisetup/cisetup.go
  go.mod
  go.sum
  utils/cliutils/codegangstautils.go
  utils/progressbar/readerprogressbar.go
  utils/tests/proxy/server/server.go
Labels: improvement

#1896 Promoted version to 2.36.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#1901 Added the Frogbot badge to the README
  README.md
Labels: improvement

#1907 Update Go to 1.20.3
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
Labels: improvement

#1906 Fix jf search tests
  go.mod
  go.sum
  utils/tests/consts.go
Labels: ignore for release

#1899 Improve unarchive inspection
  artifactory/cli.go
  documentation/CLI-for-JFrog-Artifactory.md
  go.mod
  go.sum
  plugins/commands/install.go
  schema/filespec-schema.json
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: improvement

#1911 Add Frogbot daily scan schedule and remove the frogbot-config.yml
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
Labels: improvement

#1912 Fix wrong plugins architecture linux-ppc64
  plugins/commands/utils/utils.go
Labels: bug

#1913 Update missing Linux architectures on JFrog CLI npm build scripts
  build/npm/v2-jf/README.md
  build/npm/v2-jf/init.js
  build/npm/v2-jf/package.json
  build/npm/v2/README.md
  build/npm/v2/init.js
  build/npm/v2/package.json
  documentation/JFrog-CLI.md
Labels: bug

#1916 Update Go version in transferTests to 1.20
  .github/workflows/transferTests.yml
Labels: ignore for release

#1917 Update Go version in podmanTests to 1.20
  .github/workflows/podmanTests.yml
Labels: ignore for release

#1914 Accept JFROG_CLI_BUILD_PROJECT env on download/search/props/copy commands
  artifactory/cli.go
  utils/cliutils/commandsflags.go
Labels: improvement

#1908 Support SERVER_ID environment variable
  go.mod
  go.sum
  utils/cliutils/utils.go
Labels: new feature

#1920 Update Doc links to new JFrog Help center
  general/envsetup/envsetup.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: improvement

#1921 Add retries to podman/docker tests
  docker_test.go
Labels: ignore for release

#1924 Documentation updates and fixes
  documentation/CLI-for-JFrog-Artifactory.md
  documentation/CLI-for-JFrog-Distribution.md
  documentation/CLI-for-JFrog-Mission-Control.md
  documentation/CLI-for-JFrog-Xray.md
  documentation/JFrog-CLI.md
  documentation/cli.ftmap
Labels: ignore for release
