Repository jfrog/jfrog-cli, pull requests merged in 2023-06, with the labels that each got.

#1923 Transfer config - allow providing the src work dir
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#2004 Update Go version to 1.20.4
  Jenkinsfile
Labels: improvement

#2008 Fix version check timeout
  utils/cliutils/utils.go
Labels: bug

#2010 Promoted version to 2.39.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2013 `jf audit` generates invalid JSON format
  go.mod
  go.sum
Labels: bug

#1999 Documentation updates
  documentation/JFrog-CLI.md
Labels: ignore for release

#2015 Fix the link of the header image in the JFrog CLI documentation
  documentation/JFrog-CLI.md
Labels: ignore for release

#2007 V1 - Update Go version to 1.19.9
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
Labels: safe to test, improvement

#2021 Transfer config - Fix repo does not exist issue
  go.mod
  go.sum
Labels: bug

#2026 Promote to version 2.40.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2027 Document WARN log level
  docs/common/env.go
  documentation/JFrog-CLI.md
Labels: ignore for release

#1948 New `--include` option for `jf search`
  artifactory/cli.go
  documentation/CLI-for-JFrog-Artifactory.md
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: new feature

#2017 Bug Fix - Bug - CLI upload status bar keep increasing
  go.mod
  go.sum
  utils/progressbar/filesprogressbar.go
Labels: bug

#2032 Update Go to 1.20.5
  Jenkinsfile
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
Labels: improvement

#2033 Unreleased bug upload progress bar values
  go.mod
  go.sum
Labels: ignore for release

#2047 Fix 'jf intro' command
  go.mod
  go.sum
  main.go
  main_test.go
Labels: bug

#2048 Promote to version 2.41.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2051 Fix transfer settings issue
  artifactory/cli.go
Labels: bug

#1943 Add Support for Release Bundles Create and Promote
  artifactory/cli.go
  artifactory/cli_test.go
  artifactory_test.go
  distribution/cli.go
  docs/artifactory/releasebundlecreate/help.go
  docs/artifactory/releasebundledelete/help.go
  docs/artifactory/releasebundledistribute/help.go
  docs/artifactory/releasebundlesign/help.go
  docs/artifactory/releasebundleupdate/help.go
  docs/lifecycle/create/help.go
  docs/lifecycle/promote/help.go
  documentation/CLI-for-JFrog-Lifecycle.md
  documentation/cli.ftmap
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle/cli_test.go
  lifecycle_test.go
  main.go
  main_test.go
  maven_test.go
  testdata/dev_repo_repository_config.json
  testdata/filespecs/search_all_prod_repo.json
  testdata/filespecs/upload_dev_spec_a.json
  testdata/filespecs/upload_dev_spec_b.json
  testdata/filespecs/upload_dev_spec_c.json
  testdata/lifecycle/builds-spec-1-2.json
  testdata/lifecycle/builds-spec-3.json
  testdata/lifecycle/keys/private.txt
  testdata/lifecycle/keys/public.txt
  testdata/lifecycle/release-bundles-spec.json
  testdata/prod_repo_repository_config.json
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: feature request
