Repository jfrog/jfrog-cli, pull requests merged in 2023-07, with the labels that each got.

#2058 Promote to version 2.42.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
  utils/progressbar/readerprogressbar.go
  utils/progressbar/simpleprogressbar.go
  utils/tests/utils.go
Labels: ignore for release

#2059 Avoid creating the release on GitHub
  Jenkinsfile
Labels: ignore for release

#2036 Add support for Web Login
  docs/general/login/help.go
  general/login/cli.go
  go.mod
  go.sum
  main.go
Labels: ignore for release

#2066 Curation command documentation.
  documentation/CLI-for-JFrog-Curation.md
  documentation/cli.ftmap
  documentation/images/jf-ca-output.png
Labels: ignore for release

#2072 Increase chocolatey publish retries
  Jenkinsfile
Labels: ignore for release

#2060 Multi Policies support for JFrog Curation
  go.mod
  go.sum
  scan/cli.go
  xray_test.go
Labels: improvement

#2073 Align dev branch with v2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2074 Promote to version 2.43.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2076 Respect project env var on build discard and promote
  artifactory/cli.go
  buildtools/cli.go
  utils/cliutils/utils.go
Labels: bug

#2044 New `exclusions` options for go-publish
  buildtools/cli.go
  go.mod
  go.sum
  go_test.go
  testdata/filespecs/go_publish_repo_excludes.json
  testdata/go/project3/.jfrog/projects/go.yaml
  testdata/go/project3/createGoProject_go.mod_suffix
  testdata/go/project3/dependency.go
  testdata/go/project3/go.sum
  testdata/go/project4/.jfrog/projects/go.yaml
  testdata/go/project4/createGoProject_go.mod_suffix
  testdata/go/project4/dependency.go
  testdata/go/project4/dir1/a.txt
  testdata/go/project4/dir1/dir2/b.txt
  testdata/go/project4/dir1/dir2/dir3/c.txt
  testdata/go/project4/dir4/d.txt
  testdata/go/project4/go.sum
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
  xray_test.go
Labels: new feature

#2082 Promoted version to 2.44.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2094 Dependencies Update
  go.mod
  go.sum
Labels: ignore for release

#2085 Update documentation screenshot for Multi Policies support for JFrog …
  documentation/images/jf-ca-output.png
Labels: ignore for release

#2097 Documentation updates
  README.md
  documentation/CLI-for-JFrog-Xray.md
  documentation/JFrog-CLI.md
  documentation/images/audit-contextual-analysis.png
  documentation/images/audit1.png
  documentation/images/audit2.png
  documentation/images/audit3.png
  documentation/images/jfrog-cli-intro.png
Labels: ignore for release

#2096 Docker - Fix tests
  .github/workflows/dockerTests.yml
  docker_test.go
Labels: ignore for release

#2087 Download progress bar shows incorrect values
  go.mod
  go.sum
Labels: bug

#2095 Fix pipelines sync-status command flags handling
  pipelines/cli.go
  utils/cliutils/commandsflags.go
Labels: bug

#2104 TestPoetryInstall skip date update
  utils/tests/utils.go
Labels: ignore for release

#2081 New `--module` option added to the `build-add-dependencies` command
  buildinfo_test.go
  documentation/CLI-for-JFrog-Artifactory.md
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: improvement

#2105 Transfer files - Fix repo snapshot manager error
  go.mod
  go.sum
  poetry_test.go
  transfer_test.go
  utils/tests/utils.go
Labels: bug
