Repository jfrog/jfrog-cli, pull requests merged in 2023-01, with the labels that each got.

#1792 Add terraform build info test
  artifactory_test.go
  go.mod
  go.sum
Labels: ignore for release

#1797 Fix Terraform help flags
  artifactory_test.go
  buildtools/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: bug

#1805 Add --stop option to rt transfer-files
  artifactory/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: improvement

#1802 New command - Transfer config merge
  .github/workflows/accessTests.yml
  .github/workflows/artifactoryTests.yml
  artifactory/cli.go
  artifactory_test.go
  docker_test.go
  docs/artifactory/transferconfig/help.go
  docs/artifactory/transferconfigmerge/help.go
  go.mod
  go.sum
  inttestutils/transfer.go
  main_test.go
  transfer_test.go
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: new feature

#1809 Add static analysis to test files
  .github/workflows/analysis.yml
  artifactory/cli_test.go
  artifactory_test.go
  distribution_test.go
Labels: ignore for release

#1819 Improve Access tests
  .github/workflows/accessTests.yml
  access_test.go
  main_test.go
Labels: ignore for release

#1766 New JFrog Pipelines commands
  docs/pipelines/status/help.go
  docs/pipelines/sync/help.go
  docs/pipelines/syncstatus/help.go
  docs/pipelines/trigger/help.go
  docs/pipelines/version/help.go
  go.mod
  go.sum
  main.go
  pipelines/cli.go
  utils/cliutils/cli_consts.go
  utils/cliutils/commandsflags.go
Labels: new feature
