Repository jfrog/jfrog-cli, pull requests merged in 2024-06, with the labels that each got.

#2560 Bump version from 2.57.0 to 2.57.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2562 Remove the unused `project-init` and `ci-setup` commands
  artifactory_test.go
  docs/general/cisetup/help.go
  docs/general/project/init/help.go
  general/cisetup/cisetup.go
  general/cisetup/cisetup_test.go
  general/cisetup/utils.go
  general/project/cli.go
  go.mod
  go.sum
  main.go
Labels: improvement

#2561 UX improvement for how command
  general/ai/cli.go
Labels: ignore for release

#2564 Fix Maven config freeze
  go.mod
  go.sum
Labels: bug

#2570 Bump ver from 2.58.0 to 2.58.1
  Jenkinsfile
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2572 Use almalinux:8.10 as the docker image used to create the RPM package of JFrog CLI
  Jenkinsfile
Labels: bug

#2573 Upgrade the Ubuntu version used to create JFrog CLI's debian package
  Jenkinsfile
Labels: bug

#2574 Bump version from 2.58.1 to 2.58.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2575 Fix deprecated container test syntax and update dependencies
  docker_test.go
  docs/common/env.go
  go.mod
  go.sum
  utils/tests/container.go
Labels: ignore for release

#2579 Removed the unused 'jf setup' command
  access_test.go
  general/envsetup/envsetup.go
  go.mod
  go.sum
  main.go
  utils/cliutils/commandsflags.go
Labels: improvement

#2582 Fix wrong replace on go.mod
  go.mod
  go.sum
Labels: ignore for release

#2583 Fix broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: improvement

#2585 Bump ver from 2.58.2 to 2.59.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2587 Bump ver from 2.59.0 to 2.59.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release
