Repository jfrog/jfrog-cli, pull requests merged in 2024-07, with the labels that each got.

#2596 Update dependencies
  artifactory_test.go
  general/ai/cli.go
  go.mod
  go.sum
Labels: ignore for release

#2611 Bump version from 2.59.1 to 2.60.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2610 Upgrade depedencies
  go.mod
  go.sum
Labels: ignore for release

#2609 JFrog CLI's Build - Update Go to 1.22.5
  Jenkinsfile
Labels: improvement

#2615 Upgrade the jfrog-cli-security moduke
  go.mod
  go.sum
Labels: ignore for release

#2616 Update dependencies
  .github/workflows/scriptTests.yml
  go.mod
  go.sum
Labels: ignore for release

#2618 Bump version from 2.60.0 to 2.61.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2622 JFrog CLI's RPM stopped being signed
  build/deb_rpm/v2-jf/build-scripts/pack.sh
  build/deb_rpm/v2/build-scripts/pack.sh
Labels: bug

#2623 Bump version from 2.61.0 to 2.61.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2624 Fix JFrog CLI's RPM isn't signed
  build/deb_rpm/v2-jf/build-scripts/rpm-sign.sh
  build/deb_rpm/v2/build-scripts/rpm-sign.sh
Labels: bug

#2625 Bump version from 2.61.1 to 2.61.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2626 Update dependencies
  go.mod
  go.sum
  testdata/docker/artifactory/Dockerfile
  utils/cliutils/utils.go
Labels: ignore for release

#2631 Bump ver from 2.61.2 to 2.62.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2633 Merge from dev
  artifactory/cli.go
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  general/ai/cli.go
  go.mod
  go.sum
  plugins/commands/install.go
  testdata/docker/artifactory/Dockerfile
  utils/cliutils/cli_consts.go
Labels: ignore for release
