Repository jfrog/jfrog-cli, pull requests merged in 2024-08, with the labels that each got.

#2634 Bump ver from 2.62.0 to 2.62.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2636 Updated testdata docker base image to bookworm
  testdata/docker/artifactory/Dockerfile
Labels: ignore for release

#2640 Bump ver from 2.62.1 to 2.62.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2642 Bump ver from 2.62.2 to 2.63.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2649 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#2655 Bump ver from 2.63.0 to 2.63.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2658 Update dependencies
  general/ai/cli.go
  go.mod
  go.sum
Labels: improvement

#2661 Fix proxy and certificates tests
  artifactory_test.go
Labels: ignore for release

#2663 Rename the JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL environment variable
  artifactory/cli.go
  docs/artifactory/download/help.go
  docs/common/env.go
  go.mod
  go.sum
Labels: improvement

#2660 Bump ver from 2.63.2 to 2.64.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2667 Bump version from 2.64.0 to 2.64.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2668 JFrog CLI release - Change build node
  Jenkinsfile
Labels: ignore for release

#2653 Command Summary - Invoke summary generation from the CLI
  docs/general/summary/help.go
  general/summary/cli.go
  go.mod
  go.sum
  main.go
  utils/cliutils/utils.go
Labels: improvement

#2666 Update dependencies
  general/ai/cli.go
  go.mod
  go.sum
Labels: ignore for release

#2674 Promote to version 2.65.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  general/ai/cli.go
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2676 Pull from v2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2675 Wrap CleanOldDir warning with informative message
  main.go
Labels: improvement

#2639 JFrog Curation - Support "Implicit curation" - Run curation after "install" command failure
  buildtools/cli.go
  go.mod
  go.sum
Labels: new feature
