Repository jfrog/jfrog-cli, pull requests merged in 2024-09, with the labels that each got.

#2671 Command Summary - New UI
  general/summary/cli.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: new feature

#2679 Bump version from 2.65.0 to 2.66.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2683 Aggregate code scanning sarifs from command summaries
  general/summary/cli.go
  go.mod
  go.sum
  main.go
  transfer_test.go
Labels: improvement

#2685 Merge from dev
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  buildtools/cli.go
  docs/general/summary/help.go
  general/summary/cli.go
  go.mod
  go.sum
  main.go
  transfer_test.go
  utils/cliutils/cli_consts.go
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: ignore for release

#2681 Update dependencies
  general/ai/cli.go
  go.mod
  go.sum
Labels: ignore for release

#2689 Update dependencies
  general/ai/cli.go
  go.mod
  go.sum
Labels: ignore for release

#2688 JFrog CLI Build - Upgrade go to v1.23.1
  Jenkinsfile
  README.md
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  go.mod
  go.sum
Labels: improvement

#2699 Add twine support
  .github/workflows/pythonTests.yml
  buildtools/cli.go
  docs/artifactory/twine/help.go
  go.mod
  go.sum
  pip_test.go
  testdata/pypi_local_repository_config.json
  testdata/pypi_virtual_repository_config.json
  testdata/twine/pip.yaml
  testdata/twine/pyproject/dist/jfrog_python_example-1.0-py3-none-any.whl
  testdata/twine/pyproject/dist/jfrog_python_example-1.0.tar.gz
  testdata/twine/pyproject/pyproject.toml
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: new feature

#2700 Bump ver from 2.67.0 to 2.68.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2703 Introducing JFrog CLI AI commands assistant
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  docs/general/ai/help.go
  general/ai/cli.go
  go.mod
  go.sum
  main.go
  npm_test.go
  utils/cliutils/cli_consts.go
  utils/cliutils/persistence.go
  utils/cliutils/persistence_test.go
  utils/cliutils/utils.go
  utils/cliutils/utils_test.go
Labels: new feature

#2705 Improve `jf how` AI assistant command interface UI
  general/ai/cli.go
Labels: improvement
