Repository jfrog/jfrog-cli, pull requests merged in 2024-05, with the labels that each got.

#2513 Add npm distribution tags test
  go.mod
  go.sum
  npm_test.go
Labels: ignore for release

#2530 Fix refresh tokens tests
  access_test.go
  artifactory_test.go
  go.mod
  go.sum
Labels: ignore for release

#2525 Improve help sections, add details to command descriptions and hide redundant commands
  docs/artifactory/buildaddgit/help.go
  docs/artifactory/copy/help.go
  docs/artifactory/delete/help.go
  docs/artifactory/deleteprops/help.go
  docs/artifactory/download/help.go
  docs/artifactory/groupaddusers/help.go
  docs/artifactory/move/help.go
  docs/artifactory/podmanpull/help.go
  docs/artifactory/search/help.go
  docs/artifactory/setprops/help.go
  docs/artifactory/upload/help.go
  docs/artifactory/usersdelete/help.go
  docs/common/env.go
  docs/general/invite/help.go
  general/project/cli.go
  go.mod
  go.sum
  main.go
  utils/cliutils/commandsflags.go
Labels: improvement

#2536 Fix release bundle creation with project
  artifactory/cli.go
  distribution/cli.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle/cli_test.go
  lifecycle/testdata/specfile.json
  utils/cliutils/utils.go
Labels: bug

#2539 Improve help section layout
  artifactory/cli.go
  buildtools/cli.go
  docs/artifactory/buildaddgit/help.go
  docs/artifactory/transferconfig/help.go
  docs/general/token/help.go
  main.go
Labels: improvement

#2543 Bump ver from 2.56.0 to 2.56.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2545 Fix flaky npm latest version fetch
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2540 Update go to 1.22.x
  .github/workflows/accessTests.yml
  .github/workflows/analysis.yml
  .github/workflows/artifactoryTests.yml
  .github/workflows/distributionTests.yml
  .github/workflows/dockerTests.yml
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/frogbot-scan-repository.yml
  .github/workflows/goTests.yml
  .github/workflows/gradleTests.yml
  .github/workflows/lifecycleTests.yml
  .github/workflows/mavenTests.yml
  .github/workflows/npmTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/pluginsTests.yml
  .github/workflows/podmanTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/scriptTests.yml
  .github/workflows/transferTests.yml
  Jenkinsfile
  README.md
  build/docker/full/Dockerfile
  build/docker/slim/Dockerfile
  go.mod
  go.sum
  testdata/go/simple-project/go.mod
Labels: ignore for release

#2549 Accept $schema entity in the FileSpec schema
  schema/filespec-schema.json
Labels: improvement

#2554 Embed Platform Services CLI Plugin
  go.mod
  go.sum
  main.go
Labels: safe to test, new feature

#2555 Update go.mod to 1.22.3
  go.mod
Labels: improvement

#2557 Update deps
  general/ai/cli.go
  go.mod
  go.sum
  main.go
Labels: ignore for release

#2556 Log trace ID on failure
  main.go
Labels: improvement

#2552 Command Summaries
  artifactory/cli.go
  docs/common/env.go
  go.mod
  go.sum
  utils/cliutils/utils.go
Labels: new feature

#2558 Bump version from 2.56.1 to 2.57.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2559 Improve the how command UI
  docs/general/ai/help.go
  general/ai/cli.go
Labels: ignore for release
