Repository jfrog/jfrog-cli, pull requests merged in 2024-03, with the labels that each got.

#2463 Update Windows signing
  Jenkinsfile
  build/sign/Dockerfile
Labels: improvement

#2464 Bump ver from 2.53.1 to 2.53.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2433 Artifactory Multi-Part Upload support
  artifactory/cli.go
  artifactory/cli_test.go
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
  utils/cliutils/commandsflags.go
Labels: ignore for release

#2469 Fix false positive ZipSlip when an archive entry starts with dot
  go.mod
  go.sum
Labels: bug

#2466 Add issue template chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: ignore for release

#2471 Add npm publish -workspaces test
  go.mod
  go.sum
  npm_test.go
  testdata/npm/npmworkspaces/nested1/package.json
  testdata/npm/npmworkspaces/nested2/package.json
  testdata/npm/npmworkspaces/package.json
Labels: ignore for release

#2477 Deprecate the 'jf rt atc' command
  artifactory/cli.go
Labels: improvement

#2452 Artifactory Release Lifecycle Management - Support release bundles deletion locally and remotely
  docs/lifecycle/deletelocal/help.go
  docs/lifecycle/deleteremote/help.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  utils/cliutils/commandsflags.go
Labels: new feature

#2455 Artifactory Release Lifecycle Management - Support distribution sync and project
  distribution_test.go
  go.mod
  go.sum
  lifecycle/cli.go
  utils/cliutils/commandsflags.go
Labels: new feature

#2457 Artifactory Release Lifecycle Management - Support release bundle creation by aql and artifacts, support file specs
  artifactory_test.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle/cli_test.go
  lifecycle_test.go
  schema/filespec-schema.json
  testdata/filespecs/lifecycle-aql.json
  testdata/filespecs/lifecycle-artifacts.json
  testdata/filespecs/lifecycle-builds-1-2.json
  testdata/filespecs/lifecycle-builds-3.json
  testdata/filespecs/lifecycle-release-bundles.json
  testdata/filespecs/upload_dev_spec.json
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
Labels: new feature

#2484 Transfer - Consider the MIN_CHECKSUM_DEPLOY_SIZE_KB env var
  go.mod
  go.sum
Labels: improvement

#2448 Add JFrog CLI windows binary certificate validation
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2487 Promote version to 2.54.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2488 Remove the docker --pull option from release
  Jenkinsfile
Labels: ignore for release

#2489 Simplify defer closer funcs
  .github/workflows/accessTests.yml
  .github/workflows/analysis.yml
  .github/workflows/artifactoryTests.yml
  .github/workflows/distributionTests.yml
  .github/workflows/dockerTests.yml
  .github/workflows/goTests.yml
  .github/workflows/gradleTests.yml
  .github/workflows/lifecycleTests.yml
  .github/workflows/mavenTests.yml
  .github/workflows/npmTests.yml
  .github/workflows/nugetTests.yml
  .github/workflows/pluginsTests.yml
  .github/workflows/podmanTests.yml
  .github/workflows/pythonTests.yml
  .github/workflows/scriptTests.yml
  .github/workflows/transferTests.yml
  artifactory/cli.go
  go.mod
  go.sum
  plugins/commands/install.go
  utils/cliutils/utils.go
  utils/tests/proxy/server/certificate/utils.go
  utils/tests/utils.go
Labels: ignore for release

#2486 Fix flaky lifecycle test
  lifecycle_test.go
  testdata/filespecs/upload_dev_spec_c.json
  utils/tests/consts.go
Labels: ignore for release

#2459 Artifactory Release Lifecycle Management - Add Export bundle command
  artifactory/cli.go
  artifactory/cli_test.go
  docs/lifecycle/export/help.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
Labels: new feature

#2502 Fix npm publish with provided tarball
  go.mod
  go.sum
  npm_test.go
  testdata/npm/npmprovidedtarball/jfrog-cli-tests-v1.0.0.tgz
Labels: bug

#2503 Internal cli code
  .github/workflows/analysis.yml
  .github/workflows/nugetTests.yml
  docs/general/ai/help.go
  general/ai/cli.go
  go.mod
  go.sum
  main.go
Labels: ignore for release

#2506 Modify JFrog CLI's intro message
  main.go
Labels: improvement
