Repository jfrog/jfrog-cli, pull requests merged in 2024-02, with the labels that each got.

#2425 Artifactory Release Lifecycle Management - Modify release bundle promotion properties
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  testdata/filespecs/search_all_prod_repo.json
  testdata/filespecs/search_all_prod_repo1.json
  testdata/filespecs/search_all_prod_repo2.json
  testdata/prod_repo1_repository_config.json
  testdata/prod_repo2_repository_config.json
  utils/cliutils/commandsflags.go
  utils/tests/consts.go
  utils/tests/utils.go
Labels: breaking change, improvement

#2429 Artifactory Release Lifecycle Management - Add include dependencies option to release bundle creation
  go.mod
  go.sum
  lifecycle_test.go
  testdata/lifecycle/builds-spec-3.json
Labels: new feature

#2438 Update Go to 1.20.14
  Jenkinsfile
Labels: improvement

#2437 Patch cloudflare package vulnerability: GHSA-9763-4f94-gfch
  go.mod
  go.sum
Labels: bug

#2432 Upload empty archive when all upload files were filtered out
  .github/workflows/pythonTests.yml
  artifactory_test.go
  docs/artifactory/upload/help.go
  docs/common/env.go
  go.mod
  go.sum
  plugins/commands/install.go
Labels: improvement

#2439 Hide deprecated commands from help section
  artifactory/cli.go
  docs/scan/audit/help.go
  docs/scan/auditgo/help.go
  docs/scan/auditgradle/help.go
  docs/scan/auditmvn/help.go
  docs/scan/auditnpm/help.go
  docs/scan/auditpip/help.go
  docs/scan/auditpipenv/help.go
  docs/scan/buildscan/help.go
  docs/scan/curation/help.go
  docs/scan/scan/help.go
  utils/cliutils/commandsflags.go
Labels: improvement

#2444 Add pnpm-config command
  artifactory_test.go
  buildtools/cli.go
  docs/buildtools/pnpmconfig/help.go
  go.mod
  go.sum
  utils/cliutils/commandsflags.go
Labels: new feature

#2445 Bump ver from 2.52.10 to 2.53.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2453 Update go.mod
  go.mod
  go.sum
Labels: ignore for release
