Repository jfrog/jfrog-cli, pull requests merged in 2025-02, with the labels that each got.

#2859 Update nugetTests.yml
  .github/workflows/nugetTests.yml
Labels: ignore for release

#2848 Add setup command tests for Gradle
  go.mod
  go.sum
  gradle_test.go
  testdata/gradle/setupcmd/build.gradle
  testdata/gradle/setupcmd/settings.gradle
  testdata/gradle/setupcmd/src/main/java/com/example/App.java
Labels: ignore for release

#2863 Hide setup command from help
  buildtools/cli.go
  go.mod
  go.sum
Labels: ignore for release

#2862 Bump platform-services v1.7.0
  go.mod
  go.sum
Labels: ignore for release

#2864 Bump ver from 2.73.2 to 2.73.3
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2853 Migrate distribution V1 commands definition to cli-artifactory
  distribution/cli.go
  docs/artifactory/releasebundlecreate/help.go
  docs/artifactory/releasebundledelete/help.go
  docs/artifactory/releasebundledistribute/help.go
  docs/artifactory/releasebundlesign/help.go
  docs/artifactory/releasebundleupdate/help.go
  go.mod
  go.sum
  main.go
  utils/cliutils/commandsflags.go
Labels: ignore for release

#2871 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#2877 New `promotion-type` flag for release bundle promote command
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
  utils/cliutils/commandsflags.go
Labels: improvement

#2882 Fix `rt curl` ServerID environment variable usage
  artifactory/cli.go
  artifactory_test.go
Labels: bug

#2884 Fix rbc command to accept project with no spec
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle_test.go
Labels: bug

#2893 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#2872 Adding Analyzer Manager env var to 'jf options' output
  docs/common/env.go
Labels: ignore for release

#2899 Test Stale Issues Action
  .github/workflows/staleIssues.yml
Labels: ignore for release

#2900 Add Stale Issues action
  .github/workflows/staleIssues.yml
Labels: ignore for release

#2901 Automating Inactive Issue Management
  .github/workflows/staleIssues.yml
Labels: ignore for release
