Repository jfrog/jfrog-cli, pull requests merged in 2025-06, with the labels that each got.

#2993 Fix for mismatching cpu type for macos arm64 architecture
  build/apple_release/scripts/download-signed-mac-OS-binaries.sh
Labels: bug

#3001 Bump ver from 2.76.1 to 2.77.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#3014 Add OIDC context struct
  config/cli.go
  general/token/cli.go
  go.mod
  go.sum
Labels: improvement
