Repository jfrog/jfrog-cli, pull requests merged in 2025-04, with the labels that each got.

#2940 Update Go version
  Jenkinsfile
  build/docker/slim/Dockerfile
  go.mod
  go.sum
  nuget_test.go
Labels: improvement

#2938 Add OIDC Authentication & Token Exchange Support
  .github/workflows/accessTests.yml
  .github/workflows/oidcTests.yml
  access_test.go
  config/cli.go
  docs/general/oidc/help.go
  general/token/cli.go
  go.mod
  go.sum
  main.go
  utils/cliutils/commandsflags.go
  utils/cliutils/utils.go
  utils/cliutils/utils_test.go
Labels: new feature

#2949 Bump platform-services v1.9.0
  go.mod
  go.sum
Labels: new feature

#2954 Bump ver from 2.74.1 to 2.75.0
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  go.mod
  go.sum
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2955 Fix scripts tests
  .github/workflows/scriptTests.yml
Labels: ignore for release

#2956 Fix Transfer tests
  .github/workflows/transferTests.yml
Labels: ignore for release
