Repository jfrog/jfrog-cli, pull requests merged in 2025-01, with the labels that each got.

#2819 Update GitHub bug report view to refer users to cli-security repo
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ignore for release

#2824 Fix Zsh completion
  docs/general/summary/help.go
  docs/general/token/help.go
Labels: bug

#2829 Fix lifecycle tests
  lifecycle_test.go
Labels: ignore for release

#2805 Enhance download functionality to support RBV2
  artifactory/cli.go
  artifactory_test.go
  go.mod
  go.sum
Labels: improvement

#2831 [Release Phase] - Update Signing Keys
  Jenkinsfile
Labels: bug

#2563 Sign MacOS Binaries with JFrog Certificate
  .github/workflows/prepareDarwinBinariesForRelease.yml
  Jenkinsfile
  build/apple_release/jf.app/Contents/Info.plist
  build/apple_release/jf.app/Contents/MacOs/README.md
  build/apple_release/jfrog.app/Contents/Info.plist
  build/apple_release/jfrog.app/Contents/MacOs/README.md
  build/apple_release/scripts/darwin-sign-and-notarize.sh
  build/apple_release/scripts/download-signed-mac-OS-binaries.sh
  build/apple_release/scripts/trigger-sign-mac-OS-workflow.sh
Labels: improvement

#2841 Fix Maven tests
  .github/workflows/mavenTests.yml
Labels: ignore for release

#2838 Update Dependencies & Go version to `1.23.4`
  Jenkinsfile
  go.mod
  go.sum
Labels: ignore for release

#2842 Bump version from 2.73.0 to 2.73.1
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2843 Fix release
  .github/workflows/prepareDarwinBinariesForRelease.yml
  Jenkinsfile
  build/docker/slim/Dockerfile
Labels: ignore for release

#2844 Bump version from 2.73.1 to 2.73.2
  build/npm/v2-jf/package-lock.json
  build/npm/v2-jf/package.json
  build/npm/v2/package-lock.json
  build/npm/v2/package.json
  utils/cliutils/cli_consts.go
Labels: ignore for release

#2828 Migrate artifactory commands
  artifactory/cli.go
  artifactory_test.go
  buildinfo_test.go
  buildtools/cli.go
  distribution/cli.go
  docker_test.go
  go.mod
  go.sum
  go_test.go
  gradle_test.go
  inttestutils/artifactory.go
  inttestutils/docker.go
  inttestutils/transfer.go
  maven_test.go
  npm_test.go
  nuget_test.go
  plugins/commands/publish.go
  utils/cliutils/utils.go
  utils/tests/utils.go
Labels: ignore for release

#2738 Package Manager Setup command (`Npm` `Pnpm` `Yarn` `Pip` `Pipenv` `Poetry` `Go` `Nuget` `Dotnet` `Docker` `Podman` `Maven` `Gradle`)
  .github/workflows/nugetTests.yml
  artifactory/cli.go
  buildtools/cli.go
  buildtools/help.go
  docs/buildtools/setup/help.go
  go.mod
  go.sum
  go_test.go
  maven_test.go
  npm_test.go
  nuget_test.go
  pip_test.go
  pipenv_test.go
  utils/cliutils/commandsflags.go
Labels: new feature
